[versions]
minecraft = "1.19.4"
fabric_loader = "0.14.23"
parchment_minecraft = "1.19.3"
parchment_mappings = "2023.03.12"
mappingio = "0.4.2"
fabric_loom = "1.4.1"
quilt_licenser = "2.0.1"
autoservice = "1.1.1"
autoextension = "0.1.1"
mdg_plugin = "1.4.1"
mdg_dsl = "1.5.1"
simpleci = "0.2.5"
nexuspublish = "1.3.0"
groovybundler = "1.0.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

mappingio = { module = "net.fabricmc:mapping-io", version.ref = "mappingio" }

autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }
autoextension = { module = "dev.lukebemish.autoextension:autoextension", version.ref = "autoextension" }

groovybundler = { module = "org.groovymc:groovybundler", version.ref = "groovybundler" }

# For dependabot
mdg_dsl = { module = "org.groovymc.modsdotgroovy:dsl", version.ref = "mdg_dsl" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
quilt_licenser = { id = "org.quiltmc.gradle.licenser", version.ref = "quilt_licenser" }
mdg_plugin = { id = "org.groovymc.modsdotgroovy", version.ref = "mdg_plugin" }
simpleci = { id = "org.groovymc.simpleci", version.ref = "simpleci" }
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexuspublish" }
